global:
  # Variables that are used to build env vars for the specific environment
  vars:
    ENV_NAME: "dev"
    DB_HOST: "psql-contoso-dev-swedencentral.postgres.database.azure.com"
    BASE_DB_OPTS: "ssl=true&sslmode=require"
    
    BASE_REDIS_HOST: "x-k8s-redis-headless"
    BASE_REDIS_USER: "default"
    BASE_REDIS_PASS: "mypasshere"
  # Env variables that are applied to every service
  env:
    AZURE_REGION: "swedencentral"

itgix-portal:
  enabled: true
  appId: itgix-portal
  externalsecretEnv:
    enabled: true
    secretStoreName: "secretstore-azure"
    env:
    - name: "DB_USERNAME"
      key: "itgix-portal-db-credentials"
      property: "username"
    - name: "DB_PASSWORD"
      key: "itgix-portal-db-credentials"
      property: "password"
    - name: "GOOGLE_CLIENT_ID"
      key: "itgix-portal-google-oauth"
      property: "client-id"
    - name: "GOOGLE_CLIENT_SECRET"
      key: "itgix-portal-google-oauth"
      property: "client-secret"
  cm:
    enabled: true
    env:
      APPLICATION_PORT: 8080
      DB_NAME: itgix_portal
      OAUTH_REDIRECT_URI: "https://itgix-portal.adplab.itgix.eu/login/oauth2/code/google-employee"
      FRONTEND_URL: "https://itgix-portal.adplab.itgix.eu"
      DATASOURCE_DB_URL: "jdbc:postgresql://psql-contoso-dev-swedencentral.postgres.database.azure.com:5432/itgix_portal?ssl=true&sslmode=require"
      DB_HOST: "psql-contoso-dev-swedencentral.postgres.database.azure.com"
      REGION_NAME: "swedencentral"
      AZURE_REGION: "swedencentral"
      REDIS_HOST: "x-k8s-redis-headless"
      REDIS_PORT: "6379"
      REDIS_USE_SSL: "false"
      REDIS_USERNAME: "default"

  ingress:
    enabled: true
    ingressClassName: "traefik"
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt
      traefik.ingress.kubernetes.io/router.entrypoints: websecure
      external-dns.alpha.kubernetes.io/hostname: itgix-portal.adplab.itgix.eu
    hosts:
    - host: itgix-portal.adplab.itgix.eu
      paths:
        - /
      port: 80
    tls: 
    - secretName: itgix-portal-tls
      hosts:
        - itgix-portal.adplab.itgix.eu
      enabled: true

  service:
    enabled: true
    external: false
    type: LoadBalancer
    ports:
    - name: application
      port: !!integer 80
      protocol: TCP
      targetPort: !!integer 80
      nodePort: !!integer 30001

  serviceAccount:
    enabled: true
    name: "itgix-portal-sa"
    annotations:
      azure.workload.identity/client-id: "PLACEHOLDER_WORKLOAD_IDENTITY_CLIENT_ID"

  deployment:
    enabled: true

    serviceAccountName:
      enabled: true
      name: "itgix-portal-sa"

    replicaCount: 1

    image:
      pullSecret:
        enabled: false
        secretName: "ghcr-secret"
      ecr: ""
      repository: "ghcr.io/srachevaitgix/itgix-portal/itgix-portal"
      tag: latest
      pullPolicy: "Always"

    securityContext:
      enabled: false
      runAsUser: 0
      fsGroup: 101

    ports:
    - name: application
      containerPort: 80
      protocol: TCP

    resources:
      enabled: true
      requests:
        memory: 512Mi
        cpu: 50m
      limits:
        memory: 1536Mi
        cpu: 2

    probes:
      enabled: false
      content:
        startupProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 10
          timeoutSeconds: 5
          periodSeconds: 10
          failureThreshold: 20

        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 10
          timeoutSeconds: 5
          periodSeconds: 60
          failureThreshold: 2

        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 10
          timeoutSeconds: 5
          periodSeconds: 60
          failureThreshold: 2

  jobs:
    - name: "liquibase-migrate"
      restartPolicy: Never
      serviceAccount:
        enabled: false
        name: ""
      annotations:
        # "helm.sh/hook": pre-upgrade
        # "helm.sh/hook-weight": "-5"
        # "helm.sh/hook-delete-policy": before-hook-creation
        argocd.argoproj.io/sync-wave: "-1"
        argocd.argoproj.io/hook: Sync
        argocd.argoproj.io/hook-delete-policy: BeforeHookCreation
        argocd.argoproj.io/sync-options: "Force=true,Replace=true"
      # pullSecretName: "ghcr-secret"
      image:
        digest: true
        repository: "ghcr.io/srachevaitgix/itgix-portal/itgix-portal-liquibase"
        tag: latest
        pullPolicy: "Always"
      command:
        enabled: false
        override: false
        args:
          - "/bin/sh"
          - "-c"
          - "liquibase --defaultsFile=/liquibase/liquibase.properties update"
      env: {}
      envFromCM: true
      volumes:
        cm: [ ]
        #  - cmName: some-custom-cm
        #    volName: some-custom-cm-vol
        #    mountPath: /tmp/cm
###